### ISSUE TITLE
[BUG] Client fails to load on Linux

### ISSUE THREAD

**Issue by sootysplash** [CCBlueX/LiquidBounce#1063]
### LiquidBounce Build/Version

b151fea

### Operating System

Linux

### Minecraft Version

1.19.4

### Describe the bug

Client window appears for a second, fully black and crashes several seconds later, same thing happened in the Linux version LiquidLauncher with the same error in logs, client worked perfectly in a Windows 10 VM so it's probably a Linux exclusive bug (probably, I've not been able to run any other distro of linux other than Ubuntu with Gnome). Logs specified: java.lang.UnsatisfiedLinkError: Can't load library: /home/<user>/Desktop/stuff/1.19.4 hacks/LiquidBounce/ultralight/bin/libglib-2.0-0.so

### Steps to reproduce

Run the nextgen version on LiquidBounce in any launcher with Fabric API and Fabric Kotlin API on Linux

### Client Log

```shell
[12:36:27] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[12:36:27] [main/INFO]: Loading 66 mods:
	- fabric-api 0.81.1+1.19.4
	   |-- fabric-api-base 0.4.26+1e9487d2f4
	   |-- fabric-api-lookup-api-v1 1.6.27+504944c8f4
	   |-- fabric-biome-api-v1 13.0.8+348a9c64f4
	   |-- fabric-block-api-v1 1.0.7+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.36+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.17+504944c8f4
	   |-- fabric-command-api-v1 1.2.29+f71b366ff4
	   |-- fabric-command-api-v2 2.2.8+504944c8f4
	   |-- fabric-commands-v0 0.2.46+df3654b3f4
	   |-- fabric-containers-v0 0.1.56+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.11+ae0966baf4
	   |-- fabric-convention-tags-v1 1.5.1+fe8721bef4
	   |-- fabric-crash-report-info-v1 0.2.16+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.4.2+504944c8f4
	   |-- fabric-dimensions-v1 2.1.47+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.15+504944c8f4
	   |-- fabric-events-interaction-v0 0.5.1+76ba65ebf4
	   |-- fabric-events-lifecycle-v0 0.2.54+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.34+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.19+504944c8f4
	   |-- fabric-item-group-api-v1 3.0.7+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.34+504944c8f4
	   |-- fabric-keybindings-v0 0.2.32+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.17+1e9487d2f4
	   |-- fabric-loot-api-v2 1.1.29+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.33+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.3+504944c8f4
	   |-- fabric-mining-level-api-v1 2.1.41+49abcf7ef4
	   |-- fabric-models-v0 0.3.32+504944c8f4
	   |-- fabric-networking-api-v1 1.3.3+504944c8f4
	   |-- fabric-networking-v0 0.3.43+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.5+504944c8f4
	   |-- fabric-particles-v1 1.0.25+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.10+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.2.2+504944c8f4
	   |-- fabric-renderer-api-v1 2.2.7+ebc93ff3f4
	   |-- fabric-renderer-indigo 1.2.0+ebc93ff3f4
	   |-- fabric-renderer-registries-v1 3.2.40+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.30+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.23+504944c8f4
	   |-- fabric-rendering-v0 1.1.43+df3654b3f4
	   |-- fabric-rendering-v1 2.1.3+504944c8f4
	   |-- fabric-resource-conditions-api-v1 2.3.2+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.4+5ade3c38f4
	   |-- fabric-screen-api-v1 1.0.47+3bd4ab0ff4
	   |-- fabric-screen-handler-api-v1 1.3.22+504944c8f4
	   |-- fabric-sound-api-v1 1.0.10+504944c8f4
	   |-- fabric-transfer-api-v1 3.2.0+80d07a0af4
	   \-- fabric-transitive-access-wideners-v1 3.1.1+b4a333d6f4
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.19.4
[12:36:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/heisenberg/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:36:27] [main/INFO]: Compatibility level set to JAVA_16
[12:36:27] [main/INFO]: Compatibility level set to JAVA_17
[12:36:28] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[12:36:32] [Datafixer Bootstrap/INFO]: 180 Datafixer optimizations took 90 milliseconds
[12:36:34] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:36:34] [Render thread/INFO]: Setting user: Sootysplash
[12:36:34] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[12:36:35] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[12:36:35] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[12:36:36] [Render thread/INFO]: Successfully extracted default theme
[12:36:36] [Render thread/INFO]: Loading heads...
[12:36:37] [Render thread/INFO]: Successfully loaded 956 heads from the database
[12:36:37] [Render thread/INFO]: Found out OpenGL version to be 4.6.
[12:36:37] [Render thread/INFO]: Loading ultralight...
[12:36:37] [Render thread/INFO]: Checking resources...
[12:36:37] [Render thread/INFO]: Loading ultralight natives
[12:36:37] [Render thread/INFO]: Native path: /home/<user>/Desktop/stuff/1.19.4 hacks/LiquidBounce/ultralight/bin
[12:36:37] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: Can't load library: /home/<user>/Desktop/stuff/1.19.4 hacks/LiquidBounce/ultralight/bin/libglib-2.0-0.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:139) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zlc000$liquidbounce$startClient(class_310.java:6072) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:638) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
```

**Comment by sootysplash** [comment]
I checked again and 'libglib-2.0-0.so' doesn't exist in the folder path, hope this helps.

**Comment by be4dev** [comment]
I have created a pull request, but we have to wait, until devs run linux env and test it. So the fix is installing glib and other libraries and then searching for there files and replacing ones in the /run/LiquidBounce/ultralight/bin/. If you have some problems, you can try mine https://github.com/be4dev/libraries-lb-nextgen (pls don't ban me).

**Comment by JJPMaster** [comment]
> If you have some problems, you can try mine https://github.com/be4dev/libraries-lb-nextgen (pls don't ban me).

Could you verify that this repository is public?

**Comment by be4dev** [comment]
> > If you have some problems, you can try mine https://github.com/be4dev/libraries-lb-nextgen (pls don't ban me).
> 
> Could you verify that this repository is public?

done, my fault lol

**Comment by JJPMaster** [comment]
@be4dev Using this repository throws a different error:
```[09:01:39] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[09:01:39] [main/INFO]: Loading 66 mods:
	- fabric-api 0.76.0+1.19.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
	   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.25+f71b366ff4
	   |-- fabric-command-api-v2 2.2.4+ae0966baf4
	   |-- fabric-commands-v0 0.2.42+df3654b3f4
	   |-- fabric-containers-v0 0.1.52+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
	   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.16+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.25+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
	   |-- fabric-models-v0 0.3.29+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   |-- fabric-networking-v0 0.3.39+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
	   |-- fabric-particles-v1 1.0.22+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.1.2+a383ab97f4
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
	   |-- fabric-rendering-v0 1.1.40+df3654b3f4
	   |-- fabric-rendering-v1 2.1.0+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.8+75e98211f4
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0

	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.19.4
[09:01:40] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/junie/.local/share/liquidlauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:01:40] [main/INFO]: Compatibility level set to JAVA_16
[09:01:40] [main/INFO]: Compatibility level set to JAVA_17
[09:01:41] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[09:01:49] [Datafixer Bootstrap/INFO]: 180 Datafixer optimizations took 185 milliseconds
[09:01:52] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:01:52] [Render thread/INFO]: Setting user: Supertekky
[09:01:53] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[09:01:53] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[09:01:54] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[09:01:55] [Render thread/INFO]: Successfully extracted default theme
[09:01:55] [Render thread/INFO]: Loading heads...
[09:01:56] [Render thread/INFO]: Successfully loaded 956 heads from the database
[09:01:57] [Render thread/INFO]: Found out OpenGL version to be 4.6.
[09:01:57] [Render thread/INFO]: Loading ultralight...
[09:01:57] [Render thread/INFO]: Checking resources...
[09:01:57] [Render thread/INFO]: Loading ultralight natives
[09:01:57] [Render thread/INFO]: Native path: /home/junie/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin
[09:01:57] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: /home/junie/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgobject-2.0-0.so: /home/junie/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgobject-2.0-0.so: undefined symbol: g_string_free_and_steal
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[Liqui
dBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:71) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:139) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$zla000$liquidbounce$startClient(class_310.java:6072) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:638) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
Failed to launch client: process exited unsuccessfully: exit status: 1

**Comment by JJPMaster** [comment]
Actually, nevermind; I just didn't copy the so.0 files properly; now it works.

**Comment by iFlxy** [comment]
I have the same issue.

**Comment by be4dev** [comment]
> I have the same issue.

we know, it happens on any linux, try method I mentioned above

**Comment by be4dev** [comment]
> > I have the same issue.
> 
> we know, it happens on any linux, try method I mentioned above

should be fixed now

**Comment by perdakovich** [comment]
still getting this error, even after replacing libgobject-2.0-0.so with one from this repository: https://github.com/be4dev/libraries-lb-nextgen
```
[12:27:54] [Render thread/INFO]: Loading ultralight natives
[12:27:54] [Render thread/INFO]: Native path: /home/user/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin
[12:27:54] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: /home/user/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgobject-2.0-0.so: /home/user/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgobject-2.0-0.so: undefined symbol: g_string_free_and_steal
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:145) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:71) ~[LiquidB
ounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:72) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:139) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bhc000$liquidbounce$startClient(class_310.java:9077) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Failed to launch client: process exited unsuccessfully: exit status: 1

```

**Comment by be4dev** [comment]
> undefined symbol: g_string_free_and_steal

hmm, interesting, try replacing libgobject with system one (sudo find -name "*gobject*") (if you don't have - install it)
