### ISSUE TITLE
[BUG] timer range reset

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2674]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b90 killaura f5

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

still when 10 tick plus sometimes it fails to reset anmd goes super high timer

### Steps to reproduce

turn timer raneg on 10 tick play for a bit abt 15 min then timer no reset insta ban

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
yes i haven't fix it yet.. I'll look into it soon

**Comment by EclipsesDev** [comment]
Alright fixed it, lemme know if it still happened.. i did test it and it worked, tho- I haven't fully tested it

**Comment by EclipsesDev** [comment]
also try to tune/configured the timerCharged & timerBoost option correctly

**Comment by hungrypotat** [comment]
not fixed still happened :/

**Comment by EclipsesDev** [comment]
> not fixed still happened :/

yeah maybe u need to lower ur timercharge, try that, and maybe lower a bit ur timerboost

**Comment by hungrypotat** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/d5a5ca67-8eb2-4a22-9eec-aa4be7a1634a)
this fine?

**Comment by EclipsesDev** [comment]
ur timerboost is to high lol, should at least be 4 or 7 thats should be enough, or for intave maybe lower.. thats prob why ur banned

**Comment by hungrypotat** [comment]
lemme try that, cos before it worked fine

**Comment by hungrypotat** [comment]
damn it works welp

**Comment by hungrypotat** [comment]
never mind its weird but it just stays at high timer for some reason sometimes after taking kb  or summat

**Comment by hungrypotat** [comment]
cos before this update only the 10 tick plus had this issue now 9 tick also has this issue

**Comment by EclipsesDev** [comment]
u know what, send me ur config.. I'll test it

**Comment by hungrypotat** [comment]
bruh moment
it doesnt always happen it could be 100% fine for a few matches then suddenly super flag timer
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/b32fcc4e-1d8e-4922-9412-81af5ef9965e)
also btw do u have dc lemme add u :)

**Comment by EclipsesDev** [comment]
yeah still maybe lower ur timer to like 3 or 4, it could be that intave detect timer

**Comment by hungrypotat** [comment]
nah bro i configed for a lil bit i found that u can go higher but u need to "match" the delays 
i just copied someones augustus timerrange seems fine ??

**Comment by hungrypotat** [comment]
intave is weird

**Comment by hungrypotat** [comment]
i got clip of the bug it only happens sometimes, but the config does work 100%

https://github.com/CCBlueX/LiquidBounce/assets/83085672/521b4c85-fab7-4bf0-8cdd-7e891c1f3f6d

**Comment by hungrypotat** [comment]
@EclipsesDev

**Comment by EclipsesDev** [comment]
ah def issue with the target selection thing.. I'll fix it (soon)

**Comment by EclipsesDev** [comment]
> bruh moment it doesnt always happen it could be 100% fine for a few matches then suddenly super flag timer ![image](https://private-user-images.githubusercontent.com/83085672/318261415-b32fcc4e-1d8e-4922-9412-81af5ef9965e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODEyNjcsIm5iZiI6MTcxMjU4MDk2NywicGF0aCI6Ii84MzA4NTY3Mi8zMTgyNjE0MTUtYjMyZmNjNGUtMWQ4ZS00OTIyLTk0MTItODFhZjVlZjk5NjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyNTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OTMwOTRmZWJhOTFiMTkwNTkzNmQ5YjFmMTdlYzkzMzJlYmNmZjg3MTc3YmI0MzViZjY4ZTRhNTg2NTVmMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4uvza9PBtGLLXKRcxDB_6rac5CSZga7MmcrbH5yv5jE) also btw do u have dc lemme add u :)

I use this config, and still i couldn't reproduce the same issue

**Comment by EclipsesDev** [comment]
I even tried higher ticks like 10 - 20, still couldn't reproduce the same issue

**Comment by EclipsesDev** [comment]
![Screenshot 2024-04-08 200227](https://github.com/CCBlueX/LiquidBounce/assets/99494277/38e66523-5ea0-4b9b-9c53-b2b6336a69ef)

**Comment by EclipsesDev** [comment]
oh wait, the issue is caused by ur maxangledifference setting, somehow when u set it to low like 30 it will boost ur timer longer.. hmm ig i'll fix it

**Comment by hungrypotat** [comment]
bruh

**Comment by hungrypotat** [comment]
so just leave it high

**Comment by EclipsesDev** [comment]
like 60 - 65 should be fine

**Comment by hungrypotat** [comment]
ok btw the f5 issue is still not fixed in ka

**Comment by EclipsesDev** [comment]
> ok btw the f5 issue is still not fixed in ka

send vid

**Comment by hungrypotat** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/83085672/15f8583d-2862-4630-a1b5-db2cd1cbbf72

here

**Comment by EclipsesDev** [comment]
> i.mp4 
> here

I don't quite know what happened on the video, so could u explain whats wrong?

**Comment by hungrypotat** [comment]
in killaura u know whenu go in f5 i have f5 mode disabled but it kicks me out of f5 mode

**Comment by EclipsesDev** [comment]
ah ok, will be fix in next pull

**Comment by EclipsesDev** [comment]
> ok btw the f5 issue is still not fixed in ka

fixed in #2748

**Comment by hungrypotat** [comment]
fixed

**Comment by hungrypotat** [comment]
what does stop range do cos it seems to just silent flag

**Comment by EclipsesDev** [comment]
> what does stop range do cos it seems to just silent flag

it basically doesn't allow you to timer boost at the selected stop range

**Comment by EclipsesDev** [comment]
I don't suggest using stoprange

**Comment by hungrypotat** [comment]
when will the issue bye fixed?

**Comment by EclipsesDev** [comment]
Will be fixed in b92 (I will try my best)

**Comment by EclipsesDev** [comment]
Should be fixed in b92 latest nightly build

**Comment by hungrypotat** [comment]
it isnt fixed  ait stays fast timer sometimes but logic is better :/

**Comment by hungrypotat** [comment]
it happens as i kill someone

**Comment by hungrypotat** [comment]
mostly

**Comment by EclipsesDev** [comment]
I'll fix it again later, i could fix it by old reset method, but it'll reset other timer too..

**Comment by hungrypotat** [comment]
K cool

**Comment by EclipsesDev** [comment]
ok wait I've fully fixed it

**Comment by hungrypotat** [comment]
maybe not fixed ima send clip

**Comment by hungrypotat** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/83085672/c483cb2c-dcfe-47cf-b1be-0d4a094fb80d

**Comment by EclipsesDev** [comment]
wtf, hmm can u send config? @hungrypotat

**Comment by hungrypotat** [comment]
sure bro
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/a0b7ec5a-43cc-4e8c-b999-e1b0aecb2cd5)

**Comment by EclipsesDev** [comment]
ok nvm, after testing.. its still happened mb

**Comment by hungrypotat** [comment]
O

**Comment by EclipsesDev** [comment]
ok wait i think i fixed it

**Comment by EclipsesDev** [comment]
@hungrypotat try again

**Comment by hungrypotat** [comment]
ok

**Comment by hungrypotat** [comment]
ngl finding this kinda funny

**Comment by hungrypotat** [comment]
thjink its fixed gonna test a bit more

**Comment by EclipsesDev** [comment]
> thjink its fixed gonna test a bit more

so its fixed right :] ?

**Comment by hungrypotat** [comment]
yus :)

**Comment by EclipsesDev** [comment]
noice 👍

**Comment by hungrypotat** [comment]
never mind it happens very rarely but happens once in like 70 gamres

**Comment by EclipsesDev** [comment]
> never mind it happens very rarely but happens once in like 70 gamres

Bruh.. ehh I'll look into it again ig tomorrow

**Comment by hungrypotat** [comment]
its fine take u r time :)
