### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PanboYuisshuaige** [CCBlueX/LiquidBounce#5152]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.4.1

### Operating System

Windows 10

### Minecraft Version

1.20.4,1.21,1.21.1

### Describe the bug

Prompt for resource download failure

### Steps to reproduce

I have already used VPN, but it still prompts that the download of resources has failed

### Client Log

```shell
[13:56:42] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.16.9
[13:56:42] [main/INFO]: Loading 19 mods:
	- fabric-language-kotlin 1.13.0+kotlin.2.1.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.1.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.1.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.1.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.1.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.26.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- java 17
	- liquidbounce 0.4.1
	- minecraft 1.20.4
[13:56:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/D:/PCLMC/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[13:56:42] [main/INFO]: Compatibility level set to JAVA_17
[13:56:43] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[13:56:43] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[13:56:43] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[13:56:44] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[13:56:48] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 213 milliseconds
[13:56:49] [main/ERROR]: FabricAPI is not installed, please install it to use the page buttons in the creative inventory
[13:56:49] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:56:49] [Render thread/INFO]: Setting user: CCTV14
[13:56:50] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[13:56:50] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_55608(class_310.java:467) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-6.0.52.jar:?]
	... 5 more
[13:56:51] [Render thread/INFO]: Launching LiquidBounce v0.4.1 by CCBlueX
[13:56:51] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[13:56:51] [Render thread/INFO]: Intermediary environment detected.
[13:56:51] [Render thread/INFO]: Loaded language en_us
[13:56:51] [Render thread/INFO]: Loaded language de_de
[13:56:51] [Render thread/INFO]: Loaded language ja_jp
[13:56:51] [Render thread/INFO]: Loaded language zh_cn
[13:56:51] [Render thread/INFO]: Loaded language ru_ru
[13:56:51] [Render thread/INFO]: Loaded language en_pt
[13:56:51] [Render thread/INFO]: Loaded language pt_br
[13:56:52] [Render thread/INFO]: Successfully extracted default theme
[13:56:52] [Render thread/INFO]: Inserted 10 components
[13:56:52] [Render thread/INFO]: Successfully loaded config 'enemies'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'enemies'.
[13:56:52] [Render thread/INFO]: (Chat) 
[13:56:52] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8? §7Auto ConfigAuto Config
[13:56:52] [Render thread/INFO]: Successfully loaded config 'modules'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'modules'.
[13:56:52] [Render thread/INFO]: Successfully loaded config 'commands'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'commands'.
[13:56:52] [Render thread/INFO]: Successfully loaded config 'friends'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'friends'.
[13:56:52] [Render thread/INFO]: Successfully loaded config 'proxy'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'proxy'.
[13:56:52] [Render thread/INFO]: Successfully loaded config 'accounts'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'accounts'.
[13:56:52] [Render thread/INFO]: Successfully loaded config 'tabs'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'tabs'.
[13:56:52] [Render thread/INFO]: Successfully loaded config 'lang'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'lang'.
[13:56:52] [Render thread/INFO]: Successfully loaded config 'storage'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'storage'.
[13:56:52] [Render thread/INFO]: Successfully loaded config 'theme'.
[13:56:52] [Render thread/INFO]: Successfully saved config 'theme'.
[13:56:52] [netty-websocket/INFO]: Default port 15000 available.
[13:56:52] [netty-websocket/INFO]: Starting Netty server...
[13:56:53] [nioEventLoopGroup-2-1/INFO]: [id: 0x14165a8a] REGISTERED
[13:56:53] [nioEventLoopGroup-2-1/INFO]: [id: 0x14165a8a] BIND: 0.0.0.0/0.0.0.0:15000
[13:56:53] [netty-websocket/INFO]: Netty server started on port 15000.
[13:56:53] [nioEventLoopGroup-2-1/INFO]: [id: 0x14165a8a, L:/[0:0:0:0:0:0:0:0]:15000] ACTIVE
[13:56:53] [Render thread/INFO]: Refresh Rate: 60 Hz
[13:56:53] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[13:56:53] [Render thread/INFO]: [Downloading Checksum] Started task
[13:57:14] [Render thread/ERROR]: Fatal error
java.lang.RuntimeException: Error connecting to https://dl.liquidbounce.net/resources/java-cef-builds/0e837c94ea090b6eb4b9bc65428ec28fd75d1d72/windows_amd64.tar.gz.sha256
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:261) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.compareChecksum(MCEFResourceManager.java:190) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.requiresDownload(MCEFResourceManager.java:94) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:64) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:173) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:186) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	at net.minecraft.class_310.handler$zbd000$liquidbounce$startClient(class_310.java:3350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-Fabric%200.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:112) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:105) ~[?:?]
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:233) ~[%5B1.20.4%5Dliquidbounce%200.4.1-fabric.jar:?]
	... 19 more
```

### Screenshots

![Uploading 70b84f6e616ea15a43f092291d7c8aaf.png…]()

**Comment by PanboYuisshuaige** [comment]
![70b84f6e616ea15a43f092291d7c8aaf](https://github.com/user-attachments/assets/2cd9abcb-ead0-401b-b450-c9c60fc1d5f1)

**Comment by 1zun4** [comment]
Outdated client version, no support.

**Comment by PanboYuisshuaige** [comment]
1.20.4-Fabric 0.16.9 He is already the last updated version

**Comment by 1zun4** [comment]
No, you are trying to launch a LiquidBounce version that is over a year old.

**Comment by PanboYuisshuaige** [comment]
![81ed34369d2cab3937337790626f3cd8](https://github.com/user-attachments/assets/c1979780-cb4e-450d-8780-ef25fe181192)

This is the latest LiquidLauncherr currently available 1.21.1

**Comment by 1zun4** [comment]
Something is blocking the connection. Are you sure you tried using a VPN such as Cloudflare Warp? Also check your hosts file on Windows to check if there is anything that blocks it.

**Comment by PanboYuisshuaige** [comment]
Without VPN, I am unable to access this website ：-(

**Comment by MukjepScarlet** [comment]
For JVM processes, you should use TUN mode

**Comment by MukjepScarlet** [comment]
Can you check if legacy b99 can get all online stuffs including update info/setting list?
`Caused by: java.net.ConnectException: Connection timed out: connect` 说明完全没连接上, 和HTTP客户端无关

**Comment by PanboYuisshuaige** [comment]
> 您能否检查旧版 b99 是否可以获取所有在线内容，包括更新信息/设置列表？ 说明完全没连接上， 和HTTP客户端无关`Caused by: java.net.ConnectException: Connection timed out: connect`
![44f764ed64cf7fb9504286d7e97d7c81](https://github.com/user-attachments/assets/bd5b4d6f-02f7-4c9f-aa3f-9b6262330c44)
Hello, version 1.18.1 can be opened normally

**Comment by 1zun4** [comment]
> > 您能否检查旧版 b99 是否可以获取所有在线内容，包括更新信息/设置列表？ 说明完全没连接上， 和HTTP客户端无关`Caused by: java.net.ConnectException: Connection timed out: connect`
> > ![44f764ed64cf7fb9504286d7e97d7c81](https://private-user-images.githubusercontent.com/95971465/399664279-bd5b4d6f-02f7-4c9f-aa3f-9b6262330c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTEzNTAsIm5iZiI6MTczNTgxMTA1MCwicGF0aCI6Ii85NTk3MTQ2NS8zOTk2NjQyNzktYmQ1YjRkNmYtMDJmNy00YzlmLWFhM2YtOWI2MjYyMzMwYzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDA5NDQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NzQ1MzU1NTY0NWI5OWQ1ZTZjZmQ3ZmFmN2EwNzE2NjA4Yjg1MDk3NWFlYWE4MTNiNmE0YmRhMjhhMjE5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-LEUIDnaswdSaHJ2GE_rj3ddxa3kI2ap7FqIPuhfbI)
> > Hello, version 1.18.1 can be opened normally

Yes, because it's very old and does not rely on `api.liquidbounce.net`. You are unable to connect to Cloudflare services, which seems to be a common issue in China. Use a VPN that connects from another country.

**Comment by PanboYuisshuaige** [comment]
> > > 您能否检查旧版 b99 是否可以获取所有在线内容，包括更新信息/设置列表？说明完全没连接上， 和HTTP客户端无关 ![44f764ed64cf7fb9504286d7e97d7c81](https://private-user-images.githubusercontent.com/95971465/399664279-bd5b4d6f-02f7-4c9f-aa3f-9b6262330c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTEzNTAsIm5iZiI6MTczNTgxMTA1MCwicGF0aCI6Ii85NTk3MTQ2NS8zOTk2NjQyNzktYmQ1YjRkNmYtMDJmNy00YzlmLWFhM2YtOWI2MjYyMzMwYzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDA5NDQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NzQ1MzU1NTY0NWI5OWQ1ZTZjZmQ3ZmFmN2EwNzE2NjA4Yjg1MDk3NWFlYWE4MTNiNmE0YmRhMjhhMjE5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-LEUIDnaswdSaHJ2GE_rj3ddxa3kI2ap7FqIPuhfbI) Hello， version 1.18.1 can be opened normally`Caused by: java.net.ConnectException: Connection timed out: connect`
> 
> 是的，因为它很旧，不依赖 .您无法连接到 Cloudflare 服务，这似乎是中国的一个常见问题。使用从其他国家/地区连接的 VPN。`api.liquidbounce.net`

Hello, I did encounter the same situation on another computer  ：-（

**Comment by PanboYuisshuaige** [comment]
> > > 您能否检查旧版 b99 是否可以获取所有在线内容，包括更新信息/设置列表？说明完全没连接上， 和HTTP客户端无关 ![44f764ed64cf7fb9504286d7e97d7c81](https://private-user-images.githubusercontent.com/95971465/399664279-bd5b4d6f-02f7-4c9f-aa3f-9b6262330c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTEzNTAsIm5iZiI6MTczNTgxMTA1MCwicGF0aCI6Ii85NTk3MTQ2NS8zOTk2NjQyNzktYmQ1YjRkNmYtMDJmNy00YzlmLWFhM2YtOWI2MjYyMzMwYzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDA5NDQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NzQ1MzU1NTY0NWI5OWQ1ZTZjZmQ3ZmFmN2EwNzE2NjA4Yjg1MDk3NWFlYWE4MTNiNmE0YmRhMjhhMjE5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-LEUIDnaswdSaHJ2GE_rj3ddxa3kI2ap7FqIPuhfbI) Hello， version 1.18.1 can be opened normal`Caused by: java.net.ConnectException: Connection timed out: connect`
> 
> 是的，因为它很旧，不依赖 .您无法连接到 Cloudflare 服务，这似乎是中国的一个常见问题。使用从其他国家/地区连接的 VPN。`api.liquidbounce.net`

Some people here may encounter mistakes, while others not

**Comment by 1zun4** [comment]
I will try to come up with a solution specifically for China.

**Comment by PanboYuisshuaige** [comment]
Thank you very much, author. Best wishes to you

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/ed2d2ea9-bcf6-43ea-a678-3e9cbac9b362)

Can you try this version? It now uses a different approach and it might work now.

**Comment by 1zun4** [comment]
Should be fixed with the version v0.23.0

**Comment by PanboYuisshuaige** [comment]
If I don't apply VPN, I can't open the official of liquidbounce，
I think this may be because China does not allow access to the liquidbounce website, which makes liquidbounce unavailable due to its inability to download resources
![eb5af4eabec90a4d5586f0069b922578](https://github.com/user-attachments/assets/04d466a8-7ae1-4996-932d-d70b6045f1d5)


> 应该使用版本 v0.23.0 修复

**Comment by PanboYuisshuaige** [comment]
![QQ20250103-094657](https://github.com/user-attachments/assets/4445bf35-ce2a-4a98-a1b0-9240b10b02a1)
The latest liquidbounce still cannot download resources

**Comment by MukjepScarlet** [comment]
这应该是你的网络问题, 完全连不上带CloudFlare的网站, 我可以直连

**Comment by PanboYuisshuaige** [comment]
> 这应该是你的网络问题, 完全连不上带CloudFlare的网站, 我可以直连

This may be a broadband problem. Many people have the same situation
